# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  lib,
  ...
}:
lib.flatten [
  {
    id = "ddkjiahejlhfcafbddmgiahcphecmpfh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Aa54OTC_Z65k43Frjm8X4e3Kk4vxoagEMjtZsMzPgC4LoD37cw0ZA0SxZnxtkVVh2NZ2jdPbt4hRqBIbRiY5T4ItbVWaM_cSoXxytjYiuXPVR17nqW0nwvrHqRf4n9maB2NOAMZSmuV5p2_Iostu53MXWMlNNTvzFXThLA/DDKJIAHEJLHFCAFBDDMGIAHCPHECMPFH_2026_222_1657_0.crx";
      name = "ddkjiahejlhfcafbddmgiahcphecmpfh.crx";
      hash = "sha256-GMKwpw/bLFLjufv0g5E1h0Sjcu/rmXTj4KgOCpGRhdg=";
    };
    version = "2026.222.1657";
  }
  {
    id = "oboonakemofpalcgghocfoadofidjkkk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Aa54OTBX6srMmbfBFZz5KZIGZ0tlYI_cKCA-Dlu8IsiffV_RNvF657VCISUZlSWXNREQ7-QYObny-mKNhKlVG9x_gRg62-5OECgjXZcYf5hMNcfQH5KmL6vwFyMVcstPQ74AxlKa5S2gafPaLxKMub4XAgblSJ5Dy2T3/OBOONAKEMOFPALCGGHOCFOADOFIDJKKK_1_9_11_0.crx";
      name = "oboonakemofpalcgghocfoadofidjkkk.crx";
      hash = "sha256-Xrpca6iyVN4okVLCQmrtn73dZYDP28S5LBMUX1Qz/nI=";
    };
    version = "1.9.11";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Aa54OTCD3LWkX5GO8fQKlR-nj27swxOtAHt6KOvxYamMg_G7Gp43bPi9Go_4BPuqrLpCxPGxPOq2qd7Ecup1YR2-ie47UzhGxZLRXE7S6onIOeZY_n6AdK091NH-h-IUwZoAxlKa5bxkXjh9KVOzni62MaVy9Rkif7vE/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_1_2_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-Nnud/gWl8DVIUa4g4oDYklDZclQRklHl5Uxvh/aEPYQ=";
    };
    version = "6.1.2";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Aa54OTA5Xsqagr2xxT8wcAaKrhP6FnY1iihAnJu1idp3DrmBHAZaq-noBKz82OHQ6BER-vaNdWiB6LvPC8AIjtT3-myCJSh79eG7ClQQ6TOzWLGKWZgxMQ_FzZkpV7zmU7AAxlKa5cwwRNdTDuWCrLdG2XjZ1l2ChxRn/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_26_2_19_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-af/3Kf0K5/IwRhWQne2iAl6EIPbfAHPcNVsDEH2ereg=";
    };
    version = "26.2.19";
  }
  {
    id = "gkkkcomfmldkigajkmljnbpiajbpbgdg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Aa54OTA86qOVOgOw0esprSSyf9J2-IK3581CiGyV2Xv4DXZWRckCFvkX7eYOu1xiFtNnqOLpCyzFN6Rrqw-kOe2U_p2W5hBFRDpDO-xTJ-c5xT97-5ePtwt_3OBhoQe8raAAxlKa5fKMVHmU1osMLUc8oGuDeFnFo4jO/GKKKCOMFMLDKIGAJKMLJNBPIAJBPBGDG_10_1_5_1.crx";
      name = "gkkkcomfmldkigajkmljnbpiajbpbgdg.crx";
      hash = "sha256-Patr9DmEymUGQLW+LrlM7akodgeW+GHp4uOb0Y5sSMM=";
    };
    version = "10.1.5.1";
  }
]
