# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  lib,
  ...
}:
lib.flatten [
  {
    id = "ddkjiahejlhfcafbddmgiahcphecmpfh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa46CPJFzgqSDy8Z8ejLu6cP1JdTKXjSXRFUjxSc3TznJQj4WBmcnpxoUMjsiormmbOs8cBnq1H_PsYiPFS-F9MZUa5guySFamxBgAxO9Vbji4c92cQu6k36sK4UolcuAMZSmuU-ZhSAIt7dfxaWOYHeiwEsZCcXbQ/DDKJIAHEJLHFCAFBDDMGIAHCPHECMPFH_2026_329_1951_0.crx";
      name = "ddkjiahejlhfcafbddmgiahcphecmpfh.crx";
      hash = "sha256-mwq2ydJZmcihBR9ClYvbsOC54NDPh+I6tMd2pkXtHV4=";
    };
    version = "2026.329.1951";
  }
  {
    id = "oboonakemofpalcgghocfoadofidjkkk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa4hd53h5D2CbQg8bh3L1_BTR1q9NGY1q9kaFdzeVhKmFP-NwieRubqZPNZ6oyeBqELhc80I-tHKTiakOg0Fn1IsDCbEQ3rJXu9mJYYD8SfK7E7m4ajmULGRg2bk7hcAxlKa5QiDLsmy5Y4fm9TQaGeIcRCpFPoV/OBOONAKEMOFPALCGGHOCFOADOFIDJKKK_1_10_0_1.crx";
      name = "oboonakemofpalcgghocfoadofidjkkk.crx";
      hash = "sha256-9cySMT6pNEhDaUBbr8YPwpFuMk11x6sJuZ8tB61jtg4=";
    };
    version = "1.10.0.1";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa7WmsB8SsLHgLWYbOXiZMdNSK_hqrKojmE73rxI-nIYxOmSHtainfVyok24LTWM5Bq94Nn7tBwnsho8VyNfNJgj7v1onms6ChHo5eQQln0x8NFawmEhMrfxrWyvPgYAxlKa5eA7M-mMk9RE8mrjYX0j-oJEt0uv/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_1_3_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-GvAqrQGXC/uEkm0D167S2TK8gr+ox1af0XB5zK9sxjE=";
    };
    version = "6.1.3";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa50zVMEoUChMlKfE6oyazajnqWcWVFC98k5OklPE_uC2WPV8u4xuzRlNT7gedRbHM-8P7rBiBHQbcfjANPv0DXgjdPGrwk9SmZ8XzGxY2g4uftija44SRaDV_3DDpAAxlKa5ZOuHZb6hZHkbSoDExB4EHCg2qe6/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_26_4_4_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-YENhk/gCYlW86L9NCjr0awCObGbPpEStSAKTCnRFBS4=";
    };
    version = "26.4.4";
  }
  {
    id = "gkkkcomfmldkigajkmljnbpiajbpbgdg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa4fU58KsvY6s9j9TR8rsA4wwU-wzX7VCrZ5gqDOooh7NECFarZMt276RbaIH_oInpvW9ICjkfZXf8gLk_XsiDSTX-3i3i4vP9gjkQOfj8FWEyGhDMv0Wgk73YYYyRMAxlKa5Rhv8W55XtEYMqkOYy3Cg-mut_DM/GKKKCOMFMLDKIGAJKMLJNBPIAJBPBGDG_10_1_5_1.crx";
      name = "gkkkcomfmldkigajkmljnbpiajbpbgdg.crx";
      hash = "sha256-Patr9DmEymUGQLW+LrlM7akodgeW+GHp4uOb0Y5sSMM=";
    };
    version = "10.1.5.1";
  }
  {
    id = "edibdbjcniadpccecjdfdjjppcpchdlm";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AQx-wa4YG9PMXGdmN_gd2i1CCpNxJC_sRjBJ2oVFT9_cfFpeAtLow_gN0X-QUiJB5oIy9rHrcZAeLuihJ7bg3MPD4qRzxgSswMmUQ9eSMAeoyj5bDmqfNLT0_iE_MGt4KxoAxlKa5Uf3bLLjxCLWbDQXDupTQNtJriZ9/EDIBDBJCNIADPCCECJDFDJJPPCPCHDLM_1_1_9_0.crx";
      name = "edibdbjcniadpccecjdfdjjppcpchdlm.crx";
      hash = "sha256-RrbNwwND3Sl8bTTZF5xeHMHuQEyOY7FU3vFY4TAQw30=";
    };
    version = "1.1.9";
  }
]
