# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  lib,
  ...
}:
lib.flatten [
  {
    id = "ddkjiahejlhfcafbddmgiahcphecmpfh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoer85OfGY5lkeXtLNQXWP21yOKl4I4W8ceN0z_yReSo07QCJ43cLsl6q7UMLZ7TPE9Jg72e7fgpWjUBObP2jpMJWk6RUFxMr4l9CvEM0dX7lwo9POllp1mRuIRVWTZ5WAMZSmuWBYbDfbhGWPl105WmUMd1TUcGpSg/DDKJIAHEJLHFCAFBDDMGIAHCPHECMPFH_2026_607_1724_0.crx";
      name = "ddkjiahejlhfcafbddmgiahcphecmpfh.crx";
      hash = "sha256-Q4eVNRH7uBLAvAu/wCVHn2dH0kLg27mrBuUs2Kh8T+s=";
    };
    version = "2026.607.1724";
  }
  {
    id = "oboonakemofpalcgghocfoadofidjkkk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoerScAEQg28fbKH0yqudwbNFB6LCQAyDM0T1T1T-4n23KZnBVC0m2GMPU_yq4ZEmWqsIaR0vNOZW7RwVfzO6PWAaeF-7ARuzsaqSEYlzPhSosjYTgjWRxJhyyRednJAAxlKa5Qm7oL1vEWPalWb9SQyjCDeDWljr/OBOONAKEMOFPALCGGHOCFOADOFIDJKKK_1_10_3_0.crx";
      name = "oboonakemofpalcgghocfoadofidjkkk.crx";
      hash = "sha256-wmkAetiDDZmncortFv/92K8Fm/zLfise0qAasQ4CKSU=";
    };
    version = "1.10.3";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoerGTLUdw2GfJY6ZqdJtKMBbYCDDuvjK1kYeP0QOE_ZoEuty041AVwilrpslZiUurJGkGwC13ex6dh98eRM1usj1q7PLHm6bkOKTRfz7NYXzFDRbUkZD0keVNA6jiC4AxlKa5WwbrqnJw9BX9FcXc4YI9OXLZXp-/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_1_5_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-nE5FE3Eo1jG8sT1KYjVl8JRbmAiyhN8IZObHsAIb0wY=";
    };
    version = "6.1.5";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoeperUwrqj-9hGyy_93TXayE-LDvoo16xnHl4jN9eC2grPLuezqThE6CCDW-r3taIlOiNNbwVK8KPnxKi-O2LApp4LriysIxOcG4G5dJjiHRei6KgUKQihn5ZvH8t7wAxlKa5cDuZhqIXAI-YUagXWCnAGHPx4Gw/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_26_6_7_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-Iht2QFqg3FixCfuX9fl4/SA9iXiK4x4t+vnlbS8Di1I=";
    };
    version = "26.6.7";
  }
  {
    id = "gkkkcomfmldkigajkmljnbpiajbpbgdg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoeo9QK1bNIS5ktY4HLPqO1l7q1GZ-LB4JE6RRyesCG9fCymwustKg-aMmOh-Ze4MuKmvK9op1s3m3qjO_qQBjMNmjxOOjbSy8X_is2fzbkpJ3zeK5ss_zYS9A0JHDC0AxlKa5VBxTK-zrXFVh5xMjf3spuhvG_Y5/GKKKCOMFMLDKIGAJKMLJNBPIAJBPBGDG_10_1_5_1.crx";
      name = "gkkkcomfmldkigajkmljnbpiajbpbgdg.crx";
      hash = "sha256-Patr9DmEymUGQLW+LrlM7akodgeW+GHp4uOb0Y5sSMM=";
    };
    version = "10.1.5.1";
  }
  {
    id = "edibdbjcniadpccecjdfdjjppcpchdlm";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AcPRoeq1pUf3WsKCVgtJmBvKGg1AGtUbSTbK_K75GpWZGiruQOAXq0Bx0ptrrUX0-WnP7LUWKhjZUxaBvutq70If8NuZkigPXym56BytqWBIoVTwYvh1P1Kx5vpNe7JaNwQAxlKa5Typsh4hsnIfJuwwr1b0U1Ui3be4/EDIBDBJCNIADPCCECJDFDJJPPCPCHDLM_1_1_9_0.crx";
      name = "edibdbjcniadpccecjdfdjjppcpchdlm.crx";
      hash = "sha256-RrbNwwND3Sl8bTTZF5xeHMHuQEyOY7FU3vFY4TAQw30=";
    };
    version = "1.1.9";
  }
]
