# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  lib,
  ...
}:
lib.flatten [
  {
    id = "ddkjiahejlhfcafbddmgiahcphecmpfh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Abe5cL4ivepYtQK9xaDnPa9AHNl5QZsx24qAbQifgFAXDAdvyJgI45L8vrsKsrpa1BSD7kd0dV4Qzg7yPw8Tx41YHEzrYaJ4Ruktoj2Q3yQJOxqwrb4xX38Q45M-s5IqxEcUAMZSmuUeP_hxg6KuWBNm9nEteS1YxgRPAA/DDKJIAHEJLHFCAFBDDMGIAHCPHECMPFH_2026_901_1442_0.crx";
      name = "ddkjiahejlhfcafbddmgiahcphecmpfh.crx";
      hash = "sha256-yo800GVq5teI2/k7Izp39wywxGc2gRTd8G3Qb+kpDpQ=";
    };
    version = "2026.901.1442";
  }
  {
    id = "oboonakemofpalcgghocfoadofidjkkk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Abe5cL42gitMPFzyo-YoE-LbzqoJFWzxGc-ueuwYk2GabsPaLp9ABPqlexKfYHbKRa3FdaPSSRe-nZAXIrpU_VyaZdeZIKKGVYIDHiWFwkBYCG4RvIY1vtjEmu-uuPpb3SIAxlKa5UOOVgvO2ksrFnmq2JoGG-UVXtfw/OBOONAKEMOFPALCGGHOCFOADOFIDJKKK_1_10_3_0.crx";
      name = "oboonakemofpalcgghocfoadofidjkkk.crx";
      hash = "sha256-wmkAetiDDZmncortFv/92K8Fm/zLfise0qAasQ4CKSU=";
    };
    version = "1.10.3";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Abe5cL7RCHJCj6slk2j-zacFPcXfU4A2gypDjjCZ3GIBncx9a3M3TswyPUUw7uKEWUyWiDTP3xbVQMERhNR4z595f0IH6WxySgm-BOmrulfi2YGAgJyT3Fsax3JN31x1aSYAxlKa5YnstwglTZpBrAk_jmAFtnY9HQkS/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_1_6_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-VYf+K2qZRhAcoN3nxu/nanVcXuW21uY9/EjH9zbNtP8=";
    };
    version = "6.1.6";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Abe5cL5r8msFJ1h8R0NWzcX8aifkMhxb1OoWw44mDUn7t_WrLggEUml2UjcFlu0iq1V3jBKuWVI-KDBRUTggiY7XZ23ZHcvygNWB4z824zkc0V5-dH6WtX_GDDh-B4BtVawAxlKa5XWM2V8vX4DznLqgSdZIBJ5oUAt6/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_26_9_0_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-YpNxRQ1IkD/sYTW3wSoSvlYR9kyH5i5kyB1PwEfKF/c=";
    };
    version = "26.9";
  }
  {
    id = "gkkkcomfmldkigajkmljnbpiajbpbgdg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Abe5cL5sMPxGJ2Cfxmw5xg8c9E3ZbSwrMym4kMI-vqOAsLG5RF9VR4PTwpYYF4XR9LJzoBrJHgNw_6cNkixAu98ZqG4iDC4i25gp4-ag6kt2o5vsNsRpaQY_1jPDMDIM3K8AxlKa5a8nTdqM3uW_XP89JUU5fu8FeYD_/GKKKCOMFMLDKIGAJKMLJNBPIAJBPBGDG_10_2_5_0.crx";
      name = "gkkkcomfmldkigajkmljnbpiajbpbgdg.crx";
      hash = "sha256-XMPxE3YuZ+rl/KY9Ikq69OcdeH0N7+/y0BawMxUGFCY=";
    };
    version = "10.2.5.0";
  }
  {
    id = "edibdbjcniadpccecjdfdjjppcpchdlm";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/Abe5cL5VmfPZ5IeFcHbfQUiLj9OS5Dh7KfzRbd505M83DJ3C_vdztHb5wSCiEIdD-HrZmmb8RehmNB-iWw9GWJ1toNrOurTwx6fxqZ1fbz8lMbYOLWBLkb2hykVzJ1OXt7wAxlKa5V0lhbeDulYZrMLHuONhEk392mjw/EDIBDBJCNIADPCCECJDFDJJPPCPCHDLM_1_1_9_0.crx";
      name = "edibdbjcniadpccecjdfdjjppcpchdlm.crx";
      hash = "sha256-RrbNwwND3Sl8bTTZF5xeHMHuQEyOY7FU3vFY4TAQw30=";
    };
    version = "1.1.9";
  }
]
