# This file is auto-generated by an update script
# DO NOT edit manually
{
  pkgs,
  lib,
  ...
}:
lib.flatten [
  {
    id = "ddkjiahejlhfcafbddmgiahcphecmpfh";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AZPVhcT4jFXP1FdOJ1NzdsG0Cd19HlQCH5LZUgbRnIyO8F0J9yPvzNYftoVJ7Y_qtpOP-zgBeA4tPLvBbXTwcZaaCc4sgv0MQOYFzWdMSxpJ9rpWuDky5g3C_ayVGKdrCC08AMZSmuWjASHSaAwLrGpDiIAuobZF5s-QKA/DDKJIAHEJLHFCAFBDDMGIAHCPHECMPFH_2026_920_1710_0.crx";
      name = "ddkjiahejlhfcafbddmgiahcphecmpfh.crx";
      hash = "sha256-8I+FQ79dby6znBSfA7cRlNhYCTVOkLsIdhHNerGhhGo=";
    };
    version = "2026.920.1710";
  }
  {
    id = "oboonakemofpalcgghocfoadofidjkkk";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AZPVhcQDOlLSyXZzeSSXzxpT1-utsNcs6WSkPTBQdwyowsTDKzoftE9b-O7gIIDunr2Khb25cFBe7Mi2wyTu-uiBUMbkkAd2gNpWbC1Sbfvrx9gjRQcX3FqZFwBWtUAFXbcAxlKa5aSd4YLYW5ukVzieMoFkbKHI9ISh/OBOONAKEMOFPALCGGHOCFOADOFIDJKKK_1_10_4_0.crx";
      name = "oboonakemofpalcgghocfoadofidjkkk.crx";
      hash = "sha256-VueAiAgfIO058jvmBujYOPgr1Go8fJGHtNzBvXYcA7k=";
    };
    version = "1.10.4";
  }
  {
    id = "mnjggcdmjocbbbhaepdhchncahnbgone";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AZPVhcTWfnmqjE44RBK5YQoPMBxSo1y7qcdg-DJ-fXQTElUiCRzoz076L2PnzCsPUQZqQOP-Qty-EFYPhnHaRYiJntKDMiuafq3_rcJ-LGKTOnEWoklqBe8_F207JV_shHYAxlKa5U8gzzlCzUWtqqLN4CT8eVJIRN0L/MNJGGCDMJOCBBBHAEPDHCHNCAHNBGONE_6_1_6_0.crx";
      name = "mnjggcdmjocbbbhaepdhchncahnbgone.crx";
      hash = "sha256-VYf+K2qZRhAcoN3nxu/nanVcXuW21uY9/EjH9zbNtP8=";
    };
    version = "6.1.6";
  }
  {
    id = "hlepfoohegkhhmjieoechaddaejaokhf";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AZPVhcTpwaNBPmEUBz6SRiSo4m_ET943x9ja6L8B0MLmvcjRcuf7q9CPn1gsgXj_xJJSMXWF8MwuYZW1ZYF6OWtcEKnBPOZ-u3F-U0qcosa5HdGDxAhNfEJbgA1bcNSp2u4AxlKa5T11LZVIdWadxaWfZ1x-FkJ1_WzO/HLEPFOOHEGKHHMJIEOECHADDAEJAOKHF_26_9_12_0.crx";
      name = "hlepfoohegkhhmjieoechaddaejaokhf.crx";
      hash = "sha256-6nU91pne+T/1bYhL92cn+aJbXlOyF/Pr3s+iWuJ3EXo=";
    };
    version = "26.9.12";
  }
  {
    id = "gkkkcomfmldkigajkmljnbpiajbpbgdg";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AZPVhcR39JjMCIK3Uao6R52ltlF9YeXeLjnNjUaZjev-jBEaEQk0csdJEJ1dZfqDk4kvL62zgfcmt_2frJIp0LIwsqt_PSKKEbV7JynC8TR8hQ9xG0giGk83KsUXT6ZiZDgAxlKa5YoQ4DAxInU3O7CDRjrrBhtUDMBd/GKKKCOMFMLDKIGAJKMLJNBPIAJBPBGDG_10_2_5_0.crx";
      name = "gkkkcomfmldkigajkmljnbpiajbpbgdg.crx";
      hash = "sha256-XMPxE3YuZ+rl/KY9Ikq69OcdeH0N7+/y0BawMxUGFCY=";
    };
    version = "10.2.5.0";
  }
  {
    id = "edibdbjcniadpccecjdfdjjppcpchdlm";
    crxPath = pkgs.fetchurl {
      url = "https://clients2.googleusercontent.com/crx/blobs/AZPVhcSI8tOhSxeXJ9l8JvfulnaGIYkjnULgc-g9NiptrgoklMVHIdskkf9dEEtCCMTPZezVtoC-bUKHgyv7Kp34sWh92wqGA8TNiu5GT7yIYv3c0-lU_QRhThlIPUtYp_oAxlKa5Rpvii5dNcEuOi0qGq0xW24PAJ3v/EDIBDBJCNIADPCCECJDFDJJPPCPCHDLM_1_1_9_0.crx";
      name = "edibdbjcniadpccecjdfdjjppcpchdlm.crx";
      hash = "sha256-RrbNwwND3Sl8bTTZF5xeHMHuQEyOY7FU3vFY4TAQw30=";
    };
    version = "1.1.9";
  }
]
